name: Laravel

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0.37
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: no
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.DB_DATABASE }}
          MYSQL_USER: ${{ secrets.DB_USERNAME }}
          MYSQL_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.3'
    - uses: actions/checkout@v4

    - name: Copy .env
      working-directory: backend
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Install Dependencies
      working-directory: backend
      run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Copy root .env to backend
      run: cp .env backend/.env

    - name: Generate key
      working-directory: backend
      run: php artisan key:generate

    - name: Directory Permissions
      working-directory: backend
      run: chmod -R 777 storage bootstrap/cache

    - name: Run migrations
      working-directory: backend
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: ${{ secrets.DB_DATABASE }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      run: php artisan migrate:fresh --seed

    - name: Execute tests (Unit and Feature tests) via PHPUnit
      working-directory: backend
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: ${{ secrets.DB_DATABASE }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      run: php artisan test
